name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get zig
        run: snap install zig --classic --beta

      - name: Run build and test
        run: zig build test

      - name: Run hello example
        run: ./zig-out/bin/hello --help
